#!/bin/sh
# chkconfig: 2345 85 15
# description: Starts and stops the Aerospike daemon

. /etc/rc.d/init.d/functions
. /etc/sysconfig/network
[ "$NETWORKING" = "no" ] && exit 0

ASD=/usr/bin/asd
ASDN=$(basename $ASD)
LOCKFILE=/var/lock/subsys/aerospike
CONFIG_FILE=/etc/aerospike/aerospike.conf
CMD="$ASD --config-file $CONFIG_FILE"
PIDDIR="/var/run/aerospike"
ASD_USER="aerospike"
ASD_GROUP=$ASD_USER

INITFNS=/etc/aerospike/initfns
if [ -f $INITFNS ]; then . $INITFNS; fi
if [ -n $LD_PRELOAD ]; then export LD_PRELOAD; fi

# in production, the corefiles are so huge as to prevent
# quick restarts of servers. Turn this on only if requested
# DAEMON_COREFILE_LIMIT="unlimited"

set_shmall() {
	mem=`/sbin/sysctl -n kernel.shmall`
	min=4294967296
	if [ "$mem" -lt $min ]
	then
		echo "kernel.shmall too low, setting to 4G pages"
		/sbin/sysctl -w kernel.shmall=$min
	fi
}

set_shmmax() {
	mem=`/sbin/sysctl -n kernel.shmmax`
	min=1073741824
	if [ "$mem" -lt $min ]
	then
		echo "kernel.shmmax too low, setting to 1GB"
		/sbin/sysctl -w kernel.shmmax=$min
	fi
}

#We are adding create_piddir as /var/run is tmpfs on some distributions. 
#This causes the piddir to be removed on reboot
#adding this to centos init for parity
create_piddir() {
	if [ ! -d $PIDDIR ] 
	then
		mkdir $PIDDIR
		chown $ASD_USER:$ASD_GROUP $PIDDIR
	fi
}

start() {
	ulimit -n 100000
	logger -t aerospike  "ulimit -n="`ulimit -n`
	[ -x /usr/bin/asd ] || exit 0
	set_shmall
	set_shmmax
	create_piddir
	echo -n $"Starting and checking aerospike: "
	daemon "$CMD && sleep 3 && $0 status"
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $LOCKFILE
	return $retval
}

coldstart() {
	ulimit -n 100000
	logger -t aerospike  "ulimit -n="`ulimit -n`
	[ -x /usr/bin/asd ] || exit 0
	set_shmall
	set_shmmax
	create_piddir
	echo -n $"Cold-starting aerospike: "
	daemon "$CMD --cold-start && sleep 3 && $0 status"
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $LOCKFILE
	return $retval
}

stop() {
	echo -n $"Stopping aerospike: "
	killproc $ASDN
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $LOCKFILE
	return $retval
}

rh_status() {
	status $ASDN
}

rh_status_quiet() {
	status $ASDN >/dev/null 2>&1
}

case "$1" in
	restart)
		$0 stop
		sleep 3
		$0 start
		;;
	start)
		rh_status_quiet && { echo -n "Already "; $0 status ; exit 0; }
		$1
		;;
	coldstart)
		rh_status_quiet && { echo -n "Already "; $0 status ; exit 0; }
		$1
		;;
	stop)
		rh_status_quiet || { echo -n "Already "; $0 status ; exit 0; }
		$1
		;;
	status)
		rh_status
		;;
	*)
		echo $"Usage: $0 {start|stop|status|coldstart|restart}"
		exit 2
esac
