#!/bin/tcsh -f
#
# run-under-gdb:  Run a given command line under GDB.
#

echo "\nRunning under GDB: $argv:q"

set FILE = "$argv[1]"
set ARGS = "$argv[2-]"

set CMDFILE = /tmp/gdb.$$

echo "file $FILE" > $CMDFILE
echo "set follow-fork-mode child" >> $CMDFILE
#echo "break main" >> $CMDFILE
echo "run $ARGS" >> $CMDFILE

gdb -q -x $CMDFILE

/bin/rm -f $CMDFILE

exit 0
