# Aerospike Server
# Makefile.targets
#
# Common Makefile targets, dependencies, and pattern-matching rules.
#

strip:	$(SERVER)
	$(STRIP) $(SERVER) -o $(SERVER).stripped

-include $(DEPENDENCIES)

$(OBJECT_DIR)/%.o: %.c
ifeq ($(MEXP_PHASE),1)
	$(DEPTH)/build/mexp $< $(SRCDIR)$*.c
else
  ifeq ($(MEXP_PHASE),2)
	$(CC) $(CFLAGS) $(DEF_FN) -o $@$(SUFFIX) -c $(INCLUDES) $(SRCDIR)$*.c
  else
	$(CC) $(CFLAGS) $(DEF_FN) -o $@$(SUFFIX) -c $(INCLUDES) $(SRCDIR)$<
  endif
endif
